### ISSUE TITLE
Package summary string

### ISSUE THREAD

**Issue by mlisovyi** [MouadBH/coronapy-cli#7]
The package was also added to https://github.com/soroushchehresa/awesome-coronavirus#cli :smile: 

To be stay distinct and to attract attention/contributors, I would suggest to add **python** to the package summary string

**Comment by MouadBH** [comment]
Thank you @mlisovyi for your suggestion.
How we can add python to the package summary?

**Comment by mlisovyi** [comment]
> A command line tool to fetch worldwide data about COVID-19

->

> A command line tool in python to fetch worldwide data about COVID-19
