### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by amitay87** [MouadBH/coronapy-cli#8]
i thought may be we want to implement a tab-completion for the available commands and their values (list of countries for example)

**Comment by mouadziani** [comment]
Yes, It can be very useful

**Comment by MouadBH** [comment]
Thank you @amitay87 for your suggestion, you are very welcome to contribute with us.

**Comment by amitay87** [comment]
I started to implement some basic tab completion using `alias`, `~/.bashrc`. and `complete` command, I think may be I can still refactor it to be cleaner, so currently I haven't opened a pull request yet.
Of course, you are more then welcomed to view the branch (it's just about three lines right now, I have some environment issues :-) )
https://github.com/amitay87/coronapy-cli/tree/ad_add_tab_completion
(the new file is `setup.bash` by the way - https://github.com/amitay87/coronapy-cli/blob/ad_add_tab_completion/setup)

**Comment by amitay87** [comment]
I opened a new (small) pull request, this allows a very basic and initial tab completion
https://github.com/MouadBH/coronapy-cli/pull/12
